### ISSUE TITLE
Add Support for Through Hole Headers

### ISSUE THREAD

**Issue by nealei** [faludi/xbee-smt-tht-adapter#2]
Is it possible to add support for through-hole headers like:

![image](https://user-images.githubusercontent.com/39118292/111251573-9f741000-8663-11eb-8590-976024f4fb7b.png)

**Comment by faludi** [comment]
Yes, even without the board, though for certain modules the heat sink on the PCB is highly recommended.

**Comment by nealei** [comment]
You mean yes, if I want it then do it myself? I only want the board for the heat sink.

**Comment by faludi** [comment]
Yeah, this is a project from five years ago. FWIW, I also used that radio without the heat sink and it functioned fine for me. I would never put it into a manufactured product that way, but for simple prototyping it wasn't an immediate issue.

**Comment by nealei** [comment]
![PCB](https://github.com/nebkat/xbee-smd-tht-adapter-board-reference-design/raw/master/xbee-smd-tht-pcb.png?raw=true)

https://github.com/nebkat/xbee-smd-tht-adapter-board-reference-design
